### ISSUE TITLE
Missing Content? API Overview topic

### ISSUE THREAD

**Issue by lauracly** [rackerlabs/docs-cloud-rackconnect#29]
The RackConnect API overview topic exists in the docs.rackspace.com version of the guide, but not in the staging.developer.rackspace.com version.  Was this done on purpose? Check and confirm that topic should not be in the new version.

**Comment by stanzikratel** [comment]
@lauracly I didn't do the conversion but it looks like the content that is in the RackConnect API overview topic was moved to "About the Rackconnect API" title page in the staging.developer.rackspace.com version. I think that's a good decision because we're making the content more visible. So I think we're good to go.

**Comment by DonNateR** [comment]
@lauracly In all migrated API docs, the "overview" heading should change to "About the [insert Rackspace Service here] API", per Margaret's migration instructions in the docs-migration (https://github.com/rackerlabs/docs-migration) repo.

**Comment by meker12** [comment]
OK.
